---
title: "Rossmann Sales Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


You can also embed plots, for example:


```{r}
RossmannSalesData <- read.csv("Rossmann_data_new.csv")
head(RossmannSalesData)
```

```{r}
library(ggplot2)
attach(RossmannSalesData)
ggplot(data = RossmannSalesData,aes(x=Sales)) + geom_histogram(aes(y= ..density..),binwidth = 10,colour="Red",fill="white") + geom_density(alpha="0.6",fill="white")
```

```{r}
#plots
install.packages("lmtest")
library(lmtest)
hist(Customers, probability = TRUE, ylim = c(0, 0.0020))
lines(density(Customers),col = "chocolate3",lwd = 2)
abline(v = mean(Customers),col = "royalblue",lwd = 2)
abline(v = median(Customers),col = "red",lwd = 2)
legend(x = "topright",c("Density plot", "Mean", "Median"),col = c("chocolate3", "royalblue", "red"),lwd = c(2, 2, 2))
```

```{r}
ggplot(data = RossmannSalesData,aes(x=Sales)) + geom_histogram(aes(y= ..density..),binwidth = 10,colour="blue",fill="red") + geom_density(alpha="0.6",fill="white")
```

```{r}
boxplot(Sales, col.box="plum", xlab="Sales")
```

```{r}
#Model1
m1 <- lm(Sales~ CompetitionDistance + Customers + Customers*CompetitionDistance)
dwtest(m1)
plot(m1)
```

```{r}
hist(RossmannSalesData$Sales,xlab="Sales",ylab="Frequency of Sales",border="black",col = "lightblue")
```

```{r}
hist(log(Sales),xlab="Sales",ylab="Frequency of Sales",border="black",col = "lightblue")
```

```{r}
hist(d$Customers,xlab="Customers",ylab="Frequency of Customers",border="black",col = "Green")
```

```{r}
hist(log(Customers),xlab="Customers",ylab="Frequency of Customers",border="black",col = "Green")
```

```{r}
#POOLED MODEL
install.packages("plm")
library(plm)
pool <- plm(Sales~as.factor(Assortment)+as.factor(Promo)+as.factor(Promo2)+as.factor(MONTH)+as.factor(YEAR)+Promo*CompetitionDistance,index = c("Store"),data = RossmannSalesData,model = "pooling")
```

```{r}
#The above model is not possible becuse it has duplicate values means for this model to work plm require id and year to be unique
summary(pool)
```

```{r}
hist(pool$residuals,col = "orange")
```

```{r}
RossmannSalesData[Promo==1]="YES"
RossmannSalesData[Promo==0]="NO"

class(RossmannSalesData$Promo)
any(table(RossmannSalesData$Store, RossmannSalesData$YEAR)!=1)
```

```{r}
#FUNCTION FOR FINDING DUPLICATE IN  R
with(RossmannSalesData, levels(Store)[tapply(YEAR, Store,
                               function(x) any(table(x) > 1))])
```

```{r}
#Pool model
pool_customer <- plm(Customers~as.factor(Assortment)+as.factor(Promo)+as.factor(Promo2)+as.factor(MONTH)+as.factor(YEAR)+Promo*CompetitionDistance,index = "Store",data = d,model = "pooling")
summary(pool_customer)
```

```{r}
hist(pool_customer$residuals,col = "light green")
```

```{r}
#Fixed models
w <- plm(Sales~as.factor(Promo)+as.factor(MONTH)+Promo*CompetitionDistance,index = "Store",data = RossmannSalesData,model = "within")
summary(w)
```

```{r}
hist(w$residuals,col = "light green")
```

```{r}
d <-  plm(Customers~as.factor(Promo)+as.factor(YEAR)+as.factor(SchoolHoliday),index = "Store",data = RossmannSalesData,model = "within")
summary(d)
```

```{r}
hist(d$residuals,col = "Purple")
```

```{r}
##Random effect models
random <-  plm(Sales~as.factor(Promo)+as.factor(YEAR),data = RossmannSalesData,index = c("Store"),model = "random")
summary(random)
```

```{r}
hist(random$residuals,col = "lightblue")
```

```{r}
random_customer <- plm(Customers~as.factor(Promo2)+as.factor(YEAR)+ StateHoliday,data = RossmannSalesData,index = c("Store"),model = "random")
summary(random_customer)
```

```{r}
hist(random_customer$residuals,col = "yellow")
```


